# Generated by Django 4.0.5 on 2022-06-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobro',
        ),
    ]
