# Generated by Django 4.0.5 on 2022-06-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_delete_cobro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='valor',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='valor_compras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='valor_gastos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='valor_ventas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
