# Generated by Django 4.0.5 on 2022-06-24 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_forma_pago_alter_compra_valor_compra'),
        ('administracion', '0003_remove_cierrecaja_valor_cierrecaja_valor_compras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Cuenta por pagar', 'verbose_name_plural': 'Cuentas por pagar'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='deuda',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.deuda', verbose_name='Cuenta por pagar'),
        ),
    ]
