# Generated by Django 4.0.5 on 2022-06-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_forma_pago_alter_compra_valor_compra'),
        ('administracion', '0004_alter_deuda_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra'),
        ),
    ]
