# Generated by Django 4.0.5 on 2022-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_deuda_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
