# Generated by Django 4.0.5 on 2022-06-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=128)),
                ('nit', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=128)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, null=True)),
                ('no_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('DATAFONO', 'Datafono')], default='EFECTIVO', max_length=200, null=True)),
                ('valor_compra', models.FloatField(blank=True, default=0, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.proveedor')),
            ],
        ),
    ]
