# Generated by Django 4.0.5 on 2023-01-26 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
                ('nit', models.CharField(blank=True, max_length=128, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('correo', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, null=True)),
                ('no_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito')], default='CONTADO', max_length=200, null=True)),
                ('valor_compra', models.FloatField(blank=True, null=True)),
                ('total_iva', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.proveedor')),
            ],
        ),
    ]
