# Generated by Django 4.0.5 on 2022-06-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito')], default='CONTADO', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_compra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
