# Generated by Django 4.0.5 on 2022-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_proveedor_correo_alter_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total_iva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
