# Generated by Django 4.0.5 on 2022-06-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('utilidad', models.FloatField(blank=True, null=True)),
                ('existencia', models.FloatField(blank=True, null=True)),
                ('lista_precios', models.JSONField()),
                ('archivo', models.FileField(upload_to='media')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('total_impuestos', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('utilidad', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.marca')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.unidad'),
        ),
    ]
