# Generated by Django 4.0.5 on 2022-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_utilidad_total_alter_producto_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='lista_precios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
