# Generated by Django 4.0.5 on 2022-06-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocompra',
            options={'verbose_name': 'Producto Compra', 'verbose_name_plural': 'Productos Compras'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
