# Generated by Django 4.0.5 on 2022-06-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_forma_pago_alter_compra_valor_compra'),
        ('productos', '0005_alter_productocompra_options_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.unidad'),
        ),
    ]
