# Generated by Django 4.0.5 on 2022-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_categoria_nombre_alter_marca_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocompra',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
